version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
  build:
    commands:
      - echo "Building and packaging application..."
      - mkdir -p build_output
      # Hardcoded to copy everything from a specific folder, or modify as needed
      - cp -R sampleapp-v1/* build_output/
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: 'build_output'
